/*
Student Name:Animesh Acharya
Subject:Programming fundamentals
Program:Write a program to find square of
Roll:
Lab No: 01
Date: 9/18/2016

*/

#include<stdio.h>
#include<conio.h>
void main(){
       float a, square;
       clrscr();
       printf("Enter number that you want square of");
       scanf("%f",&a);
       square = a*a;
       printf("square=%f",square);
       getch();
}








































